[package]
name = "ee-launcher"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
ee-common = { path = "../ee-common" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
